//
//  SpellModel.swift
//  DnD Spell
//
//  Created by Claudia Garofalo on 10/11/25.
//

import Foundation
import SwiftUI

class SpellModel {
    var spells : [Spell] = [
        Spell(name: "Fire Bolt", _class: "Wizard", range: "120 feet", level: 0, desc: "You hurl a mote of fire at a creature or object within range. Make a ranged spell attack against the target. On a hit, the target takes 1d10 fire damage. A flammable object hit by this spell ignites if it isn’t being worn or carried. This spell’s damage increases by 1d10 when you reach 5th level (2d10), 11th level (3d10), and 17th level (4d10).", duration: "Instantaneous", castingTime: "1 action"),
        Spell(name: "Cure Wounds", _class: "Bard", range: "Touch", level: 1, desc: "A creature you touch regains a number of hit points equal to 1d8 + your spellcasting ability modifier. This spell has no effect on undead or constructs. When you cast this spell using a spell slot of 2nd level or higher, the healing increases by 1d8 for each slot level above 1st.", duration: "Instantaneous", castingTime: "1 action"),
        Spell(name: "Rope Trick", _class: "Rogue", range: "Touch", level: 2, desc: "You touch a length of rope that is up to 60 feet long. One end of the rope then rises into the air until the whole rope hangs perpendicular to the ground. At the upper end of the rope, an invisible entrance opens to an extradimensional space that lasts until the spell ends. The extradimensional space can be reached by climbing to the top of the rope. The space can hold as many as eight Medium or smaller creatures. The rope can be pulled into the space, making the rope disappear from view outside the space. Attacks and spells can’t cross through the entrance into or out of the extradimensional space, but those inside can see out of it as if through a 3-foot-by-5-foot window centered on the rope. Anything inside the extradimensional space drops out when the spell ends.", duration: "1 hour", castingTime: "1 action"),
        Spell(name: "Tongues", _class: "Warlock", range: "Touch", level: 3, desc: "This spell grants the creature you touch the ability to understand any spoken language it hears. Moreover, when the target speaks, any creature that knows at least one language and can hear the target understands what it says.", duration: "1 hour", castingTime: "1 action"),
        Spell(name: "Grasping Vine", _class: "Druid", range: "30 feet", level: 4, desc: "You conjure a vine that sprouts from the ground in an unoccupied space of your choice that you can see within range. When you cast this spell, you can direct the vine to lash out at a creature within 30 feet of it that you can see. That creature must succeed on a Dexterity saving throw or be pulled 20 feet directly toward the vine. Until the spell ends, you can direct the vine to lash out at the same creature or another one as a bonus action on each of your turns.", duration: "Concentration, up to 1 minute", castingTime: "1 bonus action"),
        Spell(name: "Commune", _class: "Paladin", range: "Self", level: 5, desc: "You contact your deity or a divine proxy and ask up to three questions that can be answered with a yes or no. You must ask your questions before the spell ends. You receive a correct answer for each question. Divine beings aren’t necessarily omniscient, so you might receive “unclear” as an answer if a question pertains to information that lies beyond the deity’s knowledge. In a case where a one-word answer could be misleading or contrary to the deity’s interests, the DM might offer a short phrase as an answer instead. If you cast the spell two or more times before finishing your next long rest, there is a cumulative 25 percent chance for each casting after the first that you get no answer. The DM makes this roll in secret.", duration: "1 minute", castingTime: "1 minute"),
        Spell(name: "Heal", _class: "Cleric", range: "60 feet", level: 6, desc: "Choose a creature that you can see within range. A surge of positive energy washes through the creature, causing it to regain 70 hit points. The spell also ends blindness, deafness, and any diseases affecting the target. This spell has no effect on constructs or undead. At Higher Levels: When you cast this spell using a spell slot of 7th level or higher, the amount of healing increases by 10 for each slot level above 6th.", duration: "Instantaneous", castingTime: "1 action"),
        Spell(name: "Finger of Death", _class: "Sorcerer", range: "60 feet", level: 7, desc: "You send negative energy coursing through a creature that you can see within range, causing it searing pain. The target must make a Constitution saving throw. It takes 7d8+30 necrotic damage on a failed save, or half as much damage on a successful one. A humanoid killed by this spell rises at the start of your next turn as a zombie that is permanently under your command, following your verbal orders to the best of its ability.", duration: "Instantaneous", castingTime: "1 action"),
        Spell(name: "Clone", _class: "Wizard", range: "Touch", level: 8, desc: "This spell grows an inert duplicate of a living creature as a safeguard against death. This clone forms inside the vessel used in the spell's casting and grows to full size and maturity after 120 days; you can also choose to have the clone be a younger version of the same creature. It remains inert and endures indefinitely, as long as its vessel remains undisturbed. At any time after the clone matures, if the original creature dies, its soul transfers to the clone, provided that the soul is free and willing to return. The clone is physically identical to the original and has the same personality, memories, and abilities, but none of the original’s equipment. The original creature’s physical remains, if they still exist, become inert and can’t thereafter be restored to life, since the creature’s soul is elsewhere.", duration: "Instantaneous", castingTime: "1 hour"),
        Spell(name: "True Resurrection", _class: "Druid", range: "Touch", level: 9, desc: "You touch a creature that has been dead for no longer than 200 years and that died for any reason except old age. If the creature’s soul is free and willing, the creature is restored to life with all its hit points. This spell closes all wounds, neutralizes any poison, cures all diseases, and lifts any curses affecting the creature when it died. The spell replaces damaged or missing organs or limbs. If the creature was undead, it is restored to its non-undead form. The spell can even provide a new body if the original no longer exists, in which case you must speak the creature’s name. The creature then appears in an unoccupied space you choose within 10 feet of you.", duration: "Instantaneous", castingTime: "1 hour")
    ]
}
